Testing/kwsRunKWStyleTest.cxx, Utilities/KWSys/CommandLineArguments.cxx, Utilities/boost/optional/optional.hpp, Utilities/boost/utility/base_from_member.hpp, kwsCheckInternalVariables.cxx
- Updated the boost library with the latest release version (August 13th, 2015 15:23 GMT)
- Fixed warning message of KWStyle which were discovered with the following flags:
-Wunused-parameter -Wformat-nonliteral -Wdisabled-macro-expansion -Wno-sign-compare -Wtautological-compare
- Removed the following warning messages:
-/Utilities/KWSys/CommandLineArguments.cxx:616:23: warning: format string is not a string literal [-Wformat-nonliteral]
sprintf(buffer, format, argument);
^~~~~~
1 warning generated.
/Utilities/boost/optional.hpp:15:
/boost/optional/optional.hpp:1254:53: warning: 
unused parameter 'out' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
^
/Utilities/boost/optional/optional.hpp:1254:95: warning: 
unused …
=> COMP: Updated the boost library and Fixed warning messages of KWStyle 

Utilities/boost/concept_check.hpp, Utilities/boost/fusion/support/detail/result_of.hpp, Utilities/boost/static_assert.hpp
- Fixed warning messages of disabled-macro-expansion from result_of.hpp
- Fixed unused-local-typedef warning message from static_assert.hpp
- Removed unused-local-typedef warning message from concept_check.hpp
=> COMP: Fixed additional warning messages (unused-local-typedef and disabled-macro-expansion)

Utilities/boost/concept_check.hpp, Utilities/boost/xpressive/detail/dynamic/parse_charset.hpp, Utilities/boost/xpressive/detail/dynamic/parser_traits.hpp
- Fixed unused-local-typedef and unknown-pragmas warning
- Removed unused-local-typedef and unknown-pragmas warning messages by
adding the following macros:
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wall"
#endif
- Fixed shadow warning messages
- Removed the shadow warning messages by creating local variables
at the reported functions
=> COMP: Fix the addition warning messages of boost library

kwsCheckMemberFunctions.cxx, kwsCheckTypedefs.cxx
- Fix warning messages of format-string on VS 14.
- These warning messages were reported at the following page:
https://open.cdash.org/viewBuildError.php?type=1&buildid=4117158
=> COMP: Fix format-string warning messages on VS14

kwsGenerator.cxx
Some dashboard reports display errors without listing the sourcefile, this
fix prepends the filename to each error line.
Compare old:
https://open.cdash.org/viewBuildError.php?buildid=4154911
with new:
https://open.cdash.org/viewBuildError.php?buildid=4154987
New mimics how errors are reported from compilation builds.
=> ENH: Include filename with error message on dashboard reports

CMakeLists.txt, kwsCheckUsingDirectives.cxx, kwsParser.cxx, kwsParser.h, kwsStyle.cxx
__XML tag key text:__ UsingDirectives
__XML tag value:__ (0 or false to not forbid using directives; anything else to forbid them.), it's on by default
__Error type:__ USING_DIRECTIVES
__Error tag:__ UND
__New function:__ CheckUsingDirectives
__Tests:__
Except for the second test, kwsRunKWStyleTest, all tests are passing. kwsRunKWStyleTest is failing without my changes which indicates an unrelated problem (visual studio 2012 on windows).
__Note:__
Pull request #7 needs to be applied for the line numbers to be calculated correctly or use the __LineLength__ rule before this one in the xml file.
=> Added new lint rule to forbid usage of "using namespace"

CMakeLists.txt, kwsCheckRelativePathInInclude.cxx, kwsCheckUsingDirectives.cxx, kwsParser.cxx, kwsParser.h, kwsStyle.cxx
It forbids the usage of this form __"../folder/file.h"__
__XML tag key text:__ RelativePathInInclude
__XML tag value:__ (0 or false to not forbid relative path up access; anything else to forbid them.), it's on by default
__Error type:__ RELATIVE_PATH_IN_INCLUDE
__Error tag:__ RPI
__New function:__ CheckRelativePathInInclude
__Tests:__
Except for the second test, kwsRunKWStyleTest, all tests are passing. kwsRunKWStyleTest is failing without my changes which indicates an unrelated problem (visual studio 2012 on windows).
__Note:__
This branch is based off the one in pull request #8, so it includes 2 features.
Pull request #7 needs to be applied for the line numbers to be calculated correctly or use the LineLength rule before this one in the xml file.
=> Added new lint rule to forbid relative path in includes

kwsCheckIndent.cxx
Correct comparison to use IndentType enumerator TAB. Before, ErrorType
enumerator TABS was used.
=> BUG: Fix using TAB for indent checking

Utilities/boost/none.hpp
- Removed warning messages of -Wunneeded-internal-declaration by adding
the following macros.
#if defined(__clang__)
#endif
- The warning messages are reported at the following page:
https://open.cdash.org/viewBuildError.php?type=1&buildid=4161369
=> COMP: Disable warning messages of -Wunneeded-internal-declaration

kwsParser.cxx, kwsParser.h
KWStyle was only checking if string was in between double quotes. This
patch forces KWStyle to also check if the string is in between single
quotes.
Previously, the following code:
writer->SetFieldDelimiterCharacter( ',' );
would not be accepted by KWStyle if the style sheet was expecting
a space before or after a comma. This is a problem in C++ since
adding a comma between the single quote marks would change the meaning
of the code.
=> BUG: KWStyle was not checking if string was between single quotes

kwsCheckIndent.cxx
itype is a enum variable of type Indentype, assuming values SPACE (=0) and TAB (=1).
Default tab character was "space", but when itype = TAB the conditional expression
if(itype == (IndentType)TABS) 
always evaluates to false (IndentType)TABS equals 10).
=> Bugfix: checkIndent never set \t as indent character

Testing/CMakeLists.txt, Testing/KWStyleTests.cxx, Testing/kwsIndentTest.cxx, kwsCheckIndent.cxx, kwsParser.cxx
Previously would erroneously consider distant ' to be relevant to determining if a character was within 's
The logic intended to identify when a key character (e.g., a } or a { ) was within single quotes, indicating that it should be ignored.   However, it did this by counting the number of single quotes occurring before the key character.  So, if a single quote was used within a quote to indicated the possessive form of a noun, then the entire system was thrown off.   Specifically, the following code would through an error (incorrectly).
int main(int argc, char *argv[])
{
std::string x("This is my's string");
for(;;)
{
}
int a;
}
Where the "int a" is flagged as needing to be indented by 4, because the } was being ignored since it was thought to be inside of a set of ' (see "my's" …
=> BUG: Single quote check incorrect if a single quote used within a string

kwsCheckVariablePerLine.cxx
KWStyle standard (e.g., used in kwsCheckIndent and kwsCheckOperator) is to call IsBetweenChars and IsBetweenCharsFast to verify all conditions of being between parens.  
Calling only IsBetweenChars( '(', ')' ...) would fail to detect the comma being in between parens in this case:
int main ( int itkNotUsed( argc ), char * itkNotUsed( argv )[] )
or anything of similar format of adjacent parens nested within a set of parens.
Calling both IsBetweenChars and IsBetweenCharsFast resolves these and other cases encountered.
Probably need to revise implementation of both to instead have one that provides a definitive answer.
=> BUG: Must run IsBetweenChars and IsBetweenCharFast to cover all options

Utilities/boost/xpressive/sub_match.hpp
KWStyle/Utilities/boost/xpressive/sub_match.hpp:84:5: warning: declaration of ‘first’ shadows a member of ‘boost::xpressive::sub_match<__gnu_cxx::__normal_iterator > >’ [-Wshadow]
sub_match(BidiIter first, BidiIter second, bool matched_ = false)
KWStyle/Utilities/boost/xpressive/sub_match.hpp:84:5: warning: declaration of ‘second’ shadows a member of ‘boost::xpressive::sub_match<__gnu_cxx::__normal_iterator > >’ [-Wshadow]
sub_match(BidiIter first, BidiIter second, bool matched_ = false)
=> COMP: Params first and second shadowed member variables.  Renamed.

kwsCheckIndent.cxx
Now allows for typedef formatting such as
typedef typename ThisIsMyReallyLongType::Pointer
ThatMustBeWrappedToFitOnTheLine;
typedef int
MyIntType;   // Previously this would throw an error since it could fit on one line
as well as
std::cout << "Header: " << std::endl  // Notice no semicolon at the end of this line
<< "   Line after header"   // Previously this would throw an error since it could fit on one line
=> Indent with typedefs and streams

kwsCheckComma.cxx, kwsCheckIndent.cxx
Also, allow wrapping+indent in cases where the line length is less
than 90% of the max line length (instead of only allowing wrapping
+ indent if the line would exceed the maximum line length).
=> ENH: Allow for spaces after commas at the end of lines in macros.

Testing/kwsBadCharactersTest.cxx, Testing/kwsIndentTest.cxx, Testing/kwsStatementPerLineTest.cxx, Testing/kwsSwitchCaseTest.cxx, Testing/kwsVariablePerLineTest.cxx, kwsCheckLineLength.cxx, kwsParser.cxx, kwsParser.h
Fix/remove dependence on lineLength check for correct line numbers and VariablePerLine checks, fixes #48, fixes #60, fixes #82
=> Fix/remove dependence on lineLength check

kwsCheckFunctions.cxx
warning: '%ld' directive writing between 1 and 20 bytes into a region of size 10 [-Wformat-overflow=]
note: '__builtin___sprintf_chk' output between 2 and 21 bytes into a destination of size 10
=> COMP: fix potential buffer overflow

kwsCheckVariablePerLine.cxx
‘__builtin___sprintf_chk’ may write a terminating nul past the end of
the destination [-Wformat-overflow=]
=> COMP: Fix additional overflow warning

kwsParser.h
Now they are. 
Except for the second test, **kwsRunKWStyleTest**, all tests are passing. **kwsRunKWStyleTest** is failing without my changes which indicates an unrelated problem (visual studio 2012 on windows).
**Details**:
**Parser::GetLineNumber(...)** depended on that behavior so it failed except when the Line length lint rule was called before anyone tried to retrieve line numbers (it initialized the line numbers' vector).
=> Line numbers are supposed to be pre-calculated, they weren't.

kwsCheckIfNDefDefine.cxx, kwsParser.cxx, kwsParser.h
Added an option in the **IfNDefDefine** lint rule to optionally convert the pattern, consisting of filename/classname and extension to uppercase (e.g: **__TEST_H** from file **test.h**).
To use it, just add a nested option in the IfNDefDefine and set it to true or 1.
Except for the second test, **kwsRunKWStyleTest**, all tests are passing. **kwsRunKWStyleTest** is failing without my changes which indicates an unrelated problem (visual studio 2012 on windows).
Backward compatibility is maintained, the new option is off by default and not required in the xml file.
=> Feature: include guards uppercased

kwsParser.cxx
Use static_cast like the other entries. Also add const.
To address:
D:\a\1\s-build\KWStyle\kwsParser.cxx(428): warning C4267: 'initializing': conversion from 'size_t' to 'long', possible loss of data
=> COMP: Explicit size_t to long conversion

kwsCheckExtraSpaces.cxx, kwsCheckLineLength.cxx
Example message:
KWStyle/kwsCheckLineLength.cxx:83:27: warning: '%ld' directive writing between 1 and 20 bytes into a region of size 10 [-Wformat-overflow=]
=> Fix format overflow warning

KWStyleConfigure.h.in
This partially reverts commit c8344295940410ec482a92e7f19b72ca5277da3c `ENH: Use modern project command.`
It caused version to not be properly reported:
```text
$ KWStyle.exe -version
Version: ..
```
Now:
```text
$ KWStyle.exe -version
Version: 1.1.0
```
Closes #102.
=> BUG: fix reported version number

Utilities/boost/throw_exception.hpp
Silence:
```
In file included from /home/matt/src/KWStyle/Utilities/boost/smart_ptr/detail/shared_count.hpp:31:
/home/matt/src/KWStyle/Utilities/boost/throw_exception.hpp:233:105: warning: predefined identifier is only valid inside function [-Wpredefined-identifier-outside-function]
template<class E> BOOST_NORETURN void throw_with_location( E && e, boost::source_location const & loc = BOOST_CURRENT_LOCATION )
^
/home/matt/src/KWStyle/Utilities/boost/assert/source_location.hpp:104:79: note: expanded from macro 'BOOST_CURRENT_LOCATION'
^
/home/matt/src/KWStyle/Utilities/boost/current_function.hpp:37:33: note: expanded from macro 'BOOST_CURRENT_FUNCTION'
```
That is being thrown following: https://github.com/Kitware/KWStyle/pull/111
=> COMP: Ignore clang predefined-identifier-outside-function warning

kwsCheckIndent.cxx
gcc13.2 warning issued
‘__builtin___snprintf_chk’ output between 2 and 11 bytes into a destination of size 10
on ubuntu24.04 release build.
=> COMP: Fix output buffer size truncation warning

Utilities/updateBoost.sh
Fixes issue #73.
macOS dirname does not have a `--version` option, which was making the script fail on macOS.
This technique should be POSIX compliant and more crossplatform.
Solution taken from:
https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
=> Use POSIX standard technique for testing existance of a command

Testing/kwsBadCharactersTest.cxx, kwsCheckBadCharacters.cxx
Clang warned:
```
kwsCheckBadCharacters.cxx:21:54: warning: invalid UTF-8 in comment [-Winvalid-utf8]
/** Check if the current file as bad characters like <E4><FC><F6><DF>*/
^
```
The example in the comment doesn't really add anything, so just removed it.
The C++ standards committee is looking to make UTF-8 the standard portable encoding for C++ (P2295R5), so it's best that files be valid UTF-8.
There was also a test file with invalid characters, though there it was deliberate to test KWStyle's ability to detect such characters. Instead, the non-UTF8 sequences are now inserted via their hex equilavent.  Added an additional test that tried both true/false to include/exclude comment checks.
Removed pragmas that suppress warnings, now that everything is valid UTF-8.
Made some tweaks to the …
=> Make all files valid UTF8

kwsParser.cxx, kwsParser.h
removed the destructor since it didn't have copy constructor and copy assignment and there was no implementation for destructor.
it was causing -Wdeprecated-copy-with-user-provided-dtor in clang
=> removed parser Destructor

kwsCheckIfNDefDefine.cxx, kwsCheckMemberFunctions.cxx
the problem with previous one was i had a typo. it was std::string instead of std::to_string. it compiles in clang and passes the tests for me
=> fixed implicit-int-conversion warning in clang and added to_string mehod for maxlength (size_t)

kwsCheckBadCharacters.cxx, kwsCheckTabs.cxx, kwsParser.cxx, kwsPopBoostWarnings.h, kwsPushBoostWarnings.h
there are a lot of warnings originated from boost. all boost warnings for clang are disabled for boost and re enabled after boost
=> added ignore boost warnings for clang

kwsParser.cxx
changed -1 to std::string::npos to resolve Wsign-compare warnings
=> fixed clang Wsign-compare warnings

metaCommand.h
added define for METAIO_USE_NAMESPACE. I wasn't sure if it was intended to be ifdef or if so I didn't change it
=> resolved clang W-undef warnings
